apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee
  template:
    metadata:
      labels:
        app: employee
    spec:
      containers:
        - name: employee-backend
          image: 533267394261.dkr.ecr.ap-northeast-2.amazonaws.com/harbor-employee:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            limits:
              cpu: "1"
              memory: "500Mi"
            requests:
              cpu: "0.5"
              memory: "250Mi"
          ##### Kubectl secrets #####
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: db-infos
                  key: DB_HOST
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-infos
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-infos
                  key: DB_PASSWORD
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: db-infos
                  key: REDIS_HOST
            - name: JWT_SECRETKEY
              valueFrom:
                secretKeyRef:
                  name: db-infos
                  key: JWT_SECRETKEY
            - name: HOST
              valueFrom:
                secretKeyRef:
                  name: db-infos
                  key: HOST
            - name: S3KEY
              valueFrom:
                secretKeyRef:
                  name: db-infos
                  key: S3KEY
            - name: S3PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-infos
                  key: S3PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: employee-service #ingress admin name과 동일해야 한다.
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080 # admin service port
  selector:
    app: employee

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fabric8-rbac
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default # pod의 네임스페이스
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io