spring:
  application:
    name: batch-service # name 등록
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST}:3306/harbor_employee
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update #update
    show-sql: true
#    클라우더
  cloud:
    kubernetes:
      discovery:
        all-namespaces: true #모든 네임스페이스에서 활성화
  batch:
    jdbc:
      initialize-schema: ALWAYS
  redis:
    host: ${HOST}
    port: 6379