apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: salary-hpa
  labels:
    app: salary
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: salary-depl
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50