spring:
  application:
    name: salary
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST}/harbor_salary
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    kubernetes:
      discovery:
        all-namespaces: true #모든 네임스페이스에서 활성화
logging:
  level:
    root: info
    com.example.harbor_login.client: DEBUG
jwt:
  secretKey: ${JWT_SECRETKEY}
management:
  endpoints:
    web:
      exposure:
        include: "*"