name: Harbor-Login
on:
  push:
    branches:
      - harbor-login
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout github
        uses: actions/checkout@v2

      - name: install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "v1.25.9"
        id: install

      - name: configure aws
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: update cluster information
        run: aws eks update-kubeconfig --name harbor_cluster --region ap-northeast-2

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      ################ build and push #################
      ################ login #################
      - name: build and push docker image to ecr (login)
        env:
          REGISTRY: 533267394261.dkr.ecr.ap-northeast-2.amazonaws.com # ECR주소
          REPOSITORY: harbor-login
          IMAGE_TAG: latest
        run: |
          docker build \
          -t $REGISTRY/$REPOSITORY:$IMAGE_TAG \
          -f ./Harbor_Login/Dockerfile ./Harbor_Login
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      ################ apply ################

      - name: eks kubectl login apply
        run: |
          kubectl apply -f ./Harbor_Login/k8s/harbor-login-depl-serv.yml
          kubectl rollout restart deployment login-depl
